#!C:\Users\s2\riim 2026\mpcrl-greenhouse\.venv_mpcrl\Scripts\python.exe
# -*- coding: UTF-8 -*-
from __future__ import print_function, division, absolute_import

from numba.misc.numba_entry import main

if __name__ == "__main__":
    main()
